export default {
  CATE_LOADING: 'CATE_LOADING',
  CATE_DATA: 'CATE_DATA',

  RANK_LOADING: 'RANK_LOADING',
  RANK_DATA: 'RANK_DATA',

  BAG_LOADING: 'BAG_LOADING',
  BAG_DATA: 'BAG_DATA',

  SEARCH_LOADING: 'SEARCH_LOADING',
  SEARCH_DATA: 'SEARCH_DATA',

  PICK_LOADING: 'PICK_LOADING',
  PICK_DATA: 'PICK_DATA',
}
